### ISSUE TITLE
Some issues when building mbtiles file

### ISSUE THREAD

**Issue by grvance** [tmnnrs/terrain-rgb#2]
1) When following the steps of the readme we found that the minimum value reported at the gdalinfo step was -119.8 (like the old corrected line in the readme) not -23.3  - which is correct?

2) We found the final rio rgbify step threw four "Error4 file not found" but still created a (apparently) fully working mbtiles file - not sure what those errors relate to and whether there will be any anomalies lurking in our mbtiles file?

**Comment by tmnnrs** [comment]
1. Correct minimum value is -119.8 (Mountsorrel Quarry). Had an externally generated statistics file [terrain50.tif.aux.xml] which resulted in the incorrect value being returned.
2. Can't comment on this (as haven't experienced issue). MBTiles file output should be ~59.8 MB. Any errors should however be pretty apparent on a visual inspection of the dynamic hillshade.
